version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: myappdb
      JWT_SECRET: your_jwt_secret_key
    ports:
      - "3000:3000"
    depends_on:
      - db
